apiVersion: v1
kind: Service
metadata:
  name: ping-app-svc
spec:
  type: NodePort
  selector:
    app: ping-app
  ports:
    - name: log-app
      port: 2345
      protocol: TCP
      targetPort: 8080
    - name: ping-app
      port: 2346
      protocol: TCP
      targetPort: 8081