apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
  - job.yaml
  - persistentvolumeclaim.yaml
  - server-configmap.yaml
  - server-deployment.yaml
  - server-service.yaml
  - statefulset.yaml
images:
  - name: APP/IMAGE
    newName: ismayilkarimli/devops-with-kubernetes
    newTag: 3.6-app
  - name: SERVER/IMAGE
    newName: ismayilkarimli/devops-with-kubernetes
    newTag: 3.6-server
