apiVersion: v1
kind: Service
metadata:
  namespace: todo-app-ns
  name: todo-server-svc
spec:
  type: ClusterIP
  selector:
    app: todo-server
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 8081