apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-app-ns
  name: todo-app-pvc
spec:
  storageClassName: picture-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi
