apiVersion: v1
kind: Service
metadata:
  name: todo-app-server-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app-server
  ports:
    - name: server
      port: 2345
      protocol: TCP
      targetPort: 8080